### ISSUE TITLE
Transform schemas should define all Model attributes

### ISSUE THREAD

**Issue by nden** [asdf-format/asdf-transform-schemas#5]
As it stands now the converter code serializes Model attributes which are not in the schema. This means other libraries have no way of knowing that they exist and how to interpret them. Attributes like `bounding_box`, `inputs`, `outputs`, etc. should be added to the base `Transform` schema.

**Comment by WilliamJamieson** [comment]
Fixed by PRs: #31, #33, #34, and #36.
